# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooverWeb', '0003_auto_20180427_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tmp'),
        ),
    ]
