# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooverWeb', '0005_auto_20180506_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo_license',
            field=models.ImageField(blank=True, null=True, upload_to='tmp'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tmp'),
        ),
    ]
