# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooverWeb', '0007_auto_20180506_1334'),
    ]

    operations = [

    ]
