# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooverWeb', '0008_auto_20180506_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_hour',
            field=models.TimeField(),
        ),
    ]
